#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
[[ -f ~/.Xkeymap ]] && xkbcomp ~/.Xkeymap $DISPLAY
# [[ -f ~/.xmodmap.conf ]] && xmodmap ~/.xmodmap.conf

# pulseaudio --start

# exec startxfce4
# exec startkde
# exec openbox
# exec i3 -V >> ~/.i3/log 2>&1
exec gnome-session
